# Generated by Django 5.0.1 on 2024-02-06 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_detail', models.CharField(max_length=500)),
                ('order_count', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Buyers',
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_detail', models.CharField(max_length=500)),
                ('order_count', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='OrdersReceived',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.IntegerField()),
                ('item_cost', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='OrderReceived', max_length=50)),
                ('purchase_order', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('buyer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend.buyers', verbose_name='Buyers')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'OrdersReceived_table',
            },
        ),
        migrations.CreateModel(
            name='OrdersSent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.IntegerField()),
                ('item_cost', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='OrderPlaced', max_length=50)),
                ('purchase_order', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('supplier_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend.suppliers', verbose_name='Suppliers')),
            ],
            options={
                'db_table': 'OrdersSent_table',
            },
        ),
    ]
