# Generated by Django 5.0.1 on 2024-01-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyers',
            old_name='company_detail',
            new_name='buyer_detail',
        ),
        migrations.RenameField(
            model_name='buyers',
            old_name='company_name',
            new_name='buyer_name',
        ),
    ]
