# Generated by Django 5.0.1 on 2024-01-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_company_detail_buyers_buyer_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersreceived',
            name='status',
            field=models.CharField(default='OrderReceived', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderssent',
            name='status',
            field=models.CharField(default='OrderPlaced', max_length=50),
        ),
    ]
