# Generated by Django 5.0.1 on 2024-02-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_buyers_user_id_suppliers_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='buyer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_name',
            field=models.CharField(max_length=100),
        ),
    ]
