# Generated by Django 5.0.1 on 2024-01-31 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_ordersreceived_status_alter_orderssent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersreceived',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='orderssent',
            name='buyer_id',
        ),
        migrations.AddField(
            model_name='ordersreceived',
            name='buyer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend.buyers', verbose_name='Buyers'),
        ),
        migrations.AddField(
            model_name='orderssent',
            name='supplier_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend.suppliers', verbose_name='Suppliers'),
        ),
    ]
