# Generated by Django 5.0.1 on 2024-01-31 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersReceived',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.IntegerField()),
                ('item_cost', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('purchase_order', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('supplier_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='authentication.suppliers', verbose_name='Suppliers')),
            ],
            options={
                'db_table': 'OrdersReceived_table',
            },
        ),
        migrations.CreateModel(
            name='OrdersSent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_quantity', models.IntegerField()),
                ('item_cost', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('purchase_order', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('buyer_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='authentication.buyers', verbose_name='Buyers')),
            ],
            options={
                'db_table': 'OrdersSent_table',
            },
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
